CREATE TABLE `ArchitectureDesignTemplate` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `code` VARCHAR(191) NULL,
  `houseType` VARCHAR(191) NULL,
  `style` VARCHAR(191) NULL,
  `area` INTEGER NULL,
  `floors` INTEGER NULL,
  `facadeWidth` DOUBLE NULL,
  `depth` DOUBLE NULL,
  `bedrooms` INTEGER NULL,
  `bathrooms` INTEGER NULL,
  `roofType` VARCHAR(191) NULL,
  `estimatedBudget` INTEGER NULL,
  `constructionTime` VARCHAR(191) NULL,
  `location` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `contentJson` JSON NULL,
  `contentHtml` LONGTEXT NULL,
  `thumbnailMediaId` INTEGER NULL,
  `galleryMediaIds` JSON NULL,
  `metaTitle` VARCHAR(191) NULL,
  `metaDescription` TEXT NULL,
  `canonicalUrl` VARCHAR(191) NULL,
  `ogTitle` VARCHAR(191) NULL,
  `ogDescription` TEXT NULL,
  `status` ENUM('draft', 'pending_review', 'scheduled', 'published', 'archived') NOT NULL DEFAULT 'draft',
  `isFeatured` BOOLEAN NOT NULL DEFAULT false,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `publishedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `ArchitectureDesignTemplate_slug_key`(`slug`),
  INDEX `ArchitectureDesignTemplate_status_idx`(`status`),
  INDEX `ArchitectureDesignTemplate_houseType_idx`(`houseType`),
  INDEX `ArchitectureDesignTemplate_style_idx`(`style`),
  INDEX `ArchitectureDesignTemplate_roofType_idx`(`roofType`),
  INDEX `ArchitectureDesignTemplate_area_idx`(`area`),
  INDEX `ArchitectureDesignTemplate_floors_idx`(`floors`),
  INDEX `ArchitectureDesignTemplate_estimatedBudget_idx`(`estimatedBudget`),
  INDEX `ArchitectureDesignTemplate_isFeatured_idx`(`isFeatured`),
  INDEX `ArchitectureDesignTemplate_thumbnailMediaId_idx`(`thumbnailMediaId`),
  INDEX `ArchitectureDesignTemplate_publishedAt_idx`(`publishedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InteriorDesignTemplate` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `code` VARCHAR(191) NULL,
  `interiorStyle` VARCHAR(191) NULL,
  `houseType` VARCHAR(191) NULL,
  `roomType` VARCHAR(191) NULL,
  `area` INTEGER NULL,
  `layoutType` VARCHAR(191) NULL,
  `materialTone` VARCHAR(191) NULL,
  `budgetRange` VARCHAR(191) NULL,
  `budgetMin` INTEGER NULL,
  `budgetMax` INTEGER NULL,
  `location` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `contentJson` JSON NULL,
  `contentHtml` LONGTEXT NULL,
  `thumbnailMediaId` INTEGER NULL,
  `galleryMediaIds` JSON NULL,
  `metaTitle` VARCHAR(191) NULL,
  `metaDescription` TEXT NULL,
  `canonicalUrl` VARCHAR(191) NULL,
  `ogTitle` VARCHAR(191) NULL,
  `ogDescription` TEXT NULL,
  `status` ENUM('draft', 'pending_review', 'scheduled', 'published', 'archived') NOT NULL DEFAULT 'draft',
  `isFeatured` BOOLEAN NOT NULL DEFAULT false,
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `publishedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `InteriorDesignTemplate_slug_key`(`slug`),
  INDEX `InteriorDesignTemplate_status_idx`(`status`),
  INDEX `InteriorDesignTemplate_interiorStyle_idx`(`interiorStyle`),
  INDEX `InteriorDesignTemplate_houseType_idx`(`houseType`),
  INDEX `InteriorDesignTemplate_roomType_idx`(`roomType`),
  INDEX `InteriorDesignTemplate_area_idx`(`area`),
  INDEX `InteriorDesignTemplate_budgetMin_idx`(`budgetMin`),
  INDEX `InteriorDesignTemplate_budgetMax_idx`(`budgetMax`),
  INDEX `InteriorDesignTemplate_isFeatured_idx`(`isFeatured`),
  INDEX `InteriorDesignTemplate_thumbnailMediaId_idx`(`thumbnailMediaId`),
  INDEX `InteriorDesignTemplate_publishedAt_idx`(`publishedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `ArchitectureDesignTemplate`
  ADD CONSTRAINT `ArchitectureDesignTemplate_thumbnailMediaId_fkey`
  FOREIGN KEY (`thumbnailMediaId`) REFERENCES `MediaFile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `InteriorDesignTemplate`
  ADD CONSTRAINT `InteriorDesignTemplate_thumbnailMediaId_fkey`
  FOREIGN KEY (`thumbnailMediaId`) REFERENCES `MediaFile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
