/** Render-time-only canonical targets for known internal links.
 * These entries do not create server redirects or sitemap routes.
 */
export const internalCanonicalHrefTargets: Readonly<Record<string, string>> = {
  "/dich-vu-xay-nha-tron-goi-tai-ha-noi-bao-gia-minh-bach-chuyen-nghiep": "/du-an/dich-vu-xay-nha-tron-goi-tai-ha-noi-bao-gia-minh-bach-chuyen-nghiep",
  "/cach-tinh-chi-phi-xay-nha-tron-goi-khong-phat-sinh": "/du-an/cach-tinh-chi-phi-xay-nha-tron-goi-khong-phat-sinh",
  "/xay-nha-tron-goi-la-gi-co-nen-chon-dich-vu-chia-khoa-trao-tay-khong": "/du-an/xay-nha-tron-goi-la-gi-co-nen-chon-dich-vu-chia-khoa-trao-tay-khong",
  "/quy-trinh-bao-hanh-xay-nha-tron-goi-cua-hathanhhome": "/du-an/quy-trinh-bao-hanh-xay-nha-tron-goi-cua-hathanhhome",
  "/mau-hop-dong-xay-nha-tron-goi-chi-tiet-chuan-phap-ly": "/du-an/mau-hop-dong-xay-nha-tron-goi-chi-tiet-chuan-phap-ly",
  "/kinh-nghiem-xay-nha-pho-o-ha-noi-can-luu-y-nhung-gi": "/du-an/kinh-nghiem-xay-nha-pho-o-ha-noi-can-luu-y-nhung-gi",
  "/xay-nha-tron-goi-phan-tho-uy-tin-chuyen-nghiep": "/du-an/xay-nha-tron-goi-phan-tho-uy-tin-chuyen-nghiep",
  "/xay-nha-tron-goi-tay-ho-bao-gia-chi-tiet-minh-bach": "/du-an/xay-nha-tron-goi-tay-ho-bao-gia-chi-tiet-minh-bach",
  "/hoan-thien-nha-phan-tho-ha-noi-tu-van-khao-sat-mien-phi": "/du-an/hoan-thien-nha-phan-tho-ha-noi-tu-van-khao-sat-mien-phi",
  "/du-an-xay-biet-thu-nha-bac-nguyen-son-lam-tai-ha-nam": "/du-an/du-an-xay-biet-thu-nha-bac-nguyen-son-lam-tai-ha-nam",
  "/xay-nha-tron-goi-bao-nhieu-tien-1m2": "/du-an/xay-nha-tron-goi-bao-nhieu-tien-1m2",
  "/thiet-ke-noi-that-ha-noi": "/mau-thiet-ke-noi-that/thiet-ke-noi-that-ha-noi",
  "/cong-ty-xay-dung-nha-o-uy-tin-ha-noi": "/du-an/cong-ty-xay-dung-nha-o-uy-tin-ha-noi",
  "/top-sai-lam-khien-chi-phi-xay-nha-vuot-du-toan": "/du-an/top-sai-lam-khien-chi-phi-xay-nha-vuot-du-toan",
  "/xay-nha-tron-goi-ha-noi-gom-nhung-gi": "/du-an/xay-nha-tron-goi-ha-noi-gom-nhung-gi",
  "/xay-nha-tron-goi-tai-ha-noi-dich-vu-thi-cong-chuyen-nghiep": "/du-an/xay-nha-tron-goi-tai-ha-noi-dich-vu-thi-cong-chuyen-nghiep",
  "/xay-nha-tron-goi-phuong-hoan-kiem-hathanhhome": "/du-an/xay-nha-tron-goi-phuong-hoan-kiem-hathanhhome",
  "/xay-nha-tron-goi-hoai-duc-cong-ty-xay-dung-uy-tin": "/du-an/xay-nha-tron-goi-hoai-duc-cong-ty-xay-dung-uy-tin",
  "/bao-gia-xay-nha-tron-goi-tai-tuyen-quang-chi-tiet-tung-hang-muc": "/du-an/bao-gia-xay-nha-tron-goi-tai-tuyen-quang-chi-tiet-tung-hang-muc",
  "/cong-trinh-nha-o-2-tang-1tum-gia-dinh-chu-bach-co-phuong-dong-anh-ha-noi": "/du-an/cong-trinh-nha-o-2-tang-1tum-gia-dinh-chu-bach-co-phuong-dong-anh-ha-noi",
  "/cach-tinh-don-gia-xay-dung-theo-m2-chinh-xac-nhat": "/du-an/cach-tinh-don-gia-xay-dung-theo-m2-chinh-xac-nhat",
  "/xay-nha-tron-goi-long-bien-ha-noi-hathanhhome": "/du-an/xay-nha-tron-goi-long-bien-ha-noi-hathanhhome",
  "/cong-ty-xay-dung-nha-uy-tin-ha-thanh-hathanhhome": "/du-an/cong-ty-xay-dung-nha-uy-tin-ha-thanh-hathanhhome",
  "/bao-gia-xay-nha-tron-goi-tai-phuong-hoanh-bo-quang-ninh": "/du-an/bao-gia-xay-nha-tron-goi-tai-phuong-hoanh-bo-quang-ninh",
  "/xay-nha-tron-goi-tai-thach-that-bao-gia-moi-nhat-2026": "/du-an/xay-nha-tron-goi-tai-thach-that-bao-gia-moi-nhat-2026",
  "/du-an-xay-nha-o-mai-thai-2tang-phong-cach-tan-co-dien-anh-tran-quoc-an-tien-hai-thai-binh": "/du-an/du-an-xay-nha-o-mai-thai-2tang-phong-cach-tan-co-dien-anh-tran-quoc-an-tien-hai-thai-binh",
  "/bao-gia-xay-nha-tron-goi-nam-2026": "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan-cho-gia-chu",
  "/xay-nha-tron-goi-tai-thai-binh-bao-gia-quy-trinh-tu-a-z": "/du-an/xay-nha-tron-goi-tai-thai-binh-bao-gia-nam-2026-quy-trinh-tu-a-z",
  "/mau-nha-biet-thu-dep-nhat-2026": "/mau-thiet-ke-kien-truc/mau-nha-biet-thu-dep-2026",
  "/bao-gia-xay-nha-tron-goi-tai-phuong-ngo-quyen-hai-phong": "/du-an/bao-gia-xay-nha-tron-goi-2026-phuong-ngo-quyen-hai-phong",
  "/bao-gia-xay-nha-tron-goi-hathanhhome": "/du-an/bao-gia-xay-nha-tron-goi-hathanhhome-uy-tin-chat-luong",
  "/90+-mau-biet-thu-hien-dai-dep-nhat-2026": "/mau-thiet-ke-kien-truc/90-mau-biet-thu-hien-dai-dep-2026",
  "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan": "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan-cho-gia-chu",
  "/contact": "/lien-he",
  "/100+-mau-nha-pho-hien-dai-dep-nhat-2026-sang-trong-toi-uu-cong-nang-va-chi-phi-xay-dung": "/mau-thiet-ke-kien-truc/100-mau-nha-pho-hien-dai-dep-2026-sang-trong-toi-uu-cong-nang-va-chi-phi-xay-dung",
  "/100+-mau-biet-thu-hien-dai-sang-trong-xu-huong-2026": "/mau-thiet-ke-kien-truc/100-mau-biet-thu-hien-dai-sang-trong-xu-huong-2026",
  "/20-+-mau-nha-pho-5-tang-kien-truc-hien-dai-xu-huong-2026": "/mau-thiet-ke-kien-truc/20-mau-nha-pho-5-tang-kien-truc-hien-dai-xu-huong-2026",
  "/99-+-mau-nha-mai-nhat-dep-nhat-2026": "/mau-thiet-ke-kien-truc/99-mau-nha-mai-nhat-dep-2026",
  "/bao-gia-xay-nha-tron-goi-tai-thuong-tin-ha-noi": "/bao-gia-xay-nha-tron-goi-tai-thuong-tin-ha-noi-khong-phat-sinh-chi-phi",
  "/bao-gia-xay-nha-tai-phuong-hoanh-bo-quang-ninh": "/du-an/bao-gia-xay-nha-tron-goi-tai-phuong-hoanh-bo-quang-ninh",
  "/xay-nha-tron-goi-ba-vi-ho-tro-20/7-cong-ty-xay-dung-uy-tin": "/du-an/xay-nha-tron-goi-ba-vi-ho-tro-20-7-cong-ty-xay-dung-uy-tin",
};
