/** Explicit historical SEO redirects. Keep this list exact and intentionally small. */
export const legacySeoRedirects: Readonly<Record<string, string>> = {
  "/xay-nha-tron-goi": "/dich-vu/xay-nha-tron-goi",
  "/xay-nha-tron-goi-tai-ha-noi": "/du-an/xay-nha-tron-goi-tai-ha-noi-dich-vu-thi-cong-chuyen-nghiep",
  "/xay-nha-tron-goi-quan-hai-ba-trung": "/du-an/xay-nha-tron-goi-hai-ba-trung-hathanhhome",
  "/bao-gia-xay-nha-tai-quan-hoan-kiem": "/du-an/xay-nha-tron-goi-phuong-hoan-kiem-hathanhhome",
  "/bao-gia-xay-dung-nha-tron-goi-gia-re": "/du-an/bao-gia-xay-nha-tron-goi-tai-ha-noi-2026",
  "/noi-that-phong-ngu": "/mau-thiet-ke-noi-that/mau-phong-ngu-dep-am-cung-va-hien-dai",
  "/du-an/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi-hathanhhome": "/du-an/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi",
  "/mau-thiet-ke-kien-truc/35-mau-biet-thu-tan-co-dien-san-vuon-dep-nha-2026": "/mau-thiet-ke-kien-truc/35-mau-biet-thu-tan-co-dien-san-vuon-dep-2026",
  "/du-an/xay-nha-tron-goi-tai-ha-dong-khao-sat-tu-van-mien-phi": "/du-an/xay-nha-tron-goi-tai-ha-dong",
  "/du-an/cong-trinh-nha-o-biet-thu-3-tang-tai-bac-ninh-dep-hien-dai": "/du-an/cong-trinh-nha-o-biet-thu",
  "/cong-ty-noi-that-van-phong-mien-bac-uy-tin-chuyen-nghiep": "/du-an/cong-ty-noi-that-van-phong-mien-bac",
  "/xay-nha-tron-goi-ba-vi-ho-tro-24/7-cong-ty-xay-dung-uy-tin": "/du-an/xay-nha-tron-goi-ba-vi-ho-tro-20-7-cong-ty-xay-dung-uy-tin",
  "/70 -mau-biet-thu-tan-co-dien-hien-dai-dep-nha-2026": "/mau-thiet-ke-kien-truc/70-mau-biet-thu-tan-co-dien-hien-dai-dep-2026",
  "/du-an/xay-nha-tron-goi-long-bien-ha-noi": "/du-an/xay-nha-tron-goi-long-bien-ha-noi-hathanhhome",
  "/du-an/xay-nha-tron-goi-tai-ha-dong-khao-sat-tu-van-mien-phi-hathanhhome": "/du-an/xay-nha-tron-goi-tai-ha-dong",
  "/du-an/xay-nha-tron-goi-tai-nam-dinh-cap-nhat-bao-gia-moi-nhat-2026": "/du-an/cap-nhat-bao-gia-xay-nha-tron-goi-tai-nam-dinh-2026-chi-tiet-tung-hang-muc",
  "/du-an/xay-nha-tron-goi-hai-ba-trung": "/du-an/xay-nha-tron-goi-hai-ba-trung-hathanhhome",
  "/90 -mau-biet-thu-hien-dai-dep-2026": "/mau-thiet-ke-kien-truc/90-mau-biet-thu-hien-dai-dep-2026",
  "/du-an/xay-nha-tron-goi-chuong-my-cap-nhap-bao-gia-moi-nhat": "/du-an/xay-nha-tron-goi-chuong-my-cap-nhat-bao-gia-moi-nhat",
  "/99- -mau-nha-mai-nhat-dep-2026": "/mau-thiet-ke-kien-truc/99-mau-nha-mai-nhat-dep-2026",
  "/xay-nha-tron-goi-cau-giay-chuan-tien-do-hathanhhome": "/du-an/xay-nha-tron-goi-cau-giay",
  "/du-an/xay-nha-tron-goi-cau-giay-chuan-tien-do-hathanhhome": "/du-an/xay-nha-tron-goi-cau-giay",
  "/99-+-mau-nha-mai-nhat-dep-2026": "/mau-thiet-ke-kien-truc/99-mau-nha-mai-nhat-dep-2026",
  "/xay-nha-tron-goi-chuong-my-cap-nhap-bao-gia-moi-nhat": "/du-an/xay-nha-tron-goi-chuong-my-cap-nhat-bao-gia-moi-nhat",
  "/xay-nha-tron-goi-tai-ha-dong-khao-sat-tu-van-mien-phi-hathanhhome": "/du-an/xay-nha-tron-goi-tai-ha-dong",
  "/xay-nha-tron-goi-tai-vinh-phuc-bao-gia-chi-tiet-2026": "/du-an/xay-nha-tron-goi-vinh-phuc-bao-gia-chi-tiet-2026",
  "/xay-nha-tron-goi-tai-hai-duong-cap-nhap-bao-gia-moi-nhat-2026": "/du-an/xay-nha-tron-goi-tai-hai-duong-cap-nhat-bao-gia-moi-nhat2026",
  "/du-an/xay-nha-tron-goi-tai-hai-duong-cap-nhap-bao-gia-moi-nhat2026": "/du-an/xay-nha-tron-goi-tai-hai-duong-cap-nhat-bao-gia-moi-nhat2026",
  "/xay-nha-tron-goi-tai-noi-bai-ha-noi": "/du-an/xay-nha-tron-goi-xa-noi-bai-ha-noi",
  "/xay-nha-tron-goi-tai-phuong-ba-dinh": "/du-an/xay-nha-tron-goi-ba-dinh-ha-noi-cong-ty-xay-dung-uy-tin",
  "/cong-trinh-biet-thu-nha-vuon-ninh-binh": "/du-an/cong-trinh-biet-thu-nha-vuon-nha-anh-tran-cao-cuong-ninh-binh",
  "/Cong-trinh-biet-thu-nha-vuon-ninh-binh": "/du-an/cong-trinh-biet-thu-nha-vuon-nha-anh-tran-cao-cuong-ninh-binh",
  "/bao-gia-xay-nha-tai-tien-du-bac-ninh-uy-tin-chat-luong": "/du-an/bao-gia-xay-nha-tron-goi-tai-tien-du-bac-ninh-uy-tin-chat-luong",
  "/xay-nha-tron-goi-o-hoang-mai-bao-gia-chi-tiet-nhat-hathanhhome": "/du-an/xay-nha-tron-goi-o-hoang-mai-bao-gia-chi-tiet",
  "/xay-nha-tron-goi-dong-da-bao-hanh-dai-han-hathanhhome": "/du-an/xay-nha-tron-goi-dong-da-bao-hanh-dai-han",
  "/bao-gia-xay-nha-tron-goi-tai-ninh-binh-moi-nhat-2026-cong-ty-xay-dung-uy-tin": "/du-an/bao-gia-xay-nha-tron-goi-tai-ninh-binh-nam-2026",
  "/xay-nha-tron-goi-tai-dong-anh-don-vi-thi-cong-chuyen-nghiep-ha-thanh-home": "/du-an/xay-nha-tron-goi-dong-anh-don-vi-thi-cong-chuyen-nghiep",
  "/xat-nha-tron-goi-tai-phuc-tho-cap-nhap-bao-gia-moi-nhat-hien-nay": "/du-an/xay-nha-tron-goi-phuc-tho-cap-nhat-bao-gia-nam-2026",
  "/xay-nha-tron-goi-tai-nam-dinh-cap-nhat-bao-gia-moi-nhat-2026": "/du-an/cap-nhat-bao-gia-xay-nha-tron-goi-tai-nam-dinh-2026-chi-tiet-tung-hang-muc",
  "/bao-gia-xay-nha-tron-goi-tai-ha-noi-minh-bach-ha-thanh-home": "/du-an/bao-gia-xay-nha-tron-goi-tai-ha-noi-2026",
  "/bao-gia-xay-nha-tron-goi-ha-thanh-home-uy-tin-chat-luong": "/du-an/bao-gia-xay-nha-tron-goi-hathanhhome-uy-tin-chat-luong",
  "/xay-nha-tron-goi-tai-son-tay-cam-ket-chuan-tien-do": "/du-an/xay-nha-tron-goi-son-tay-cam-ket-chuan-tien-do",
  "/xay-nha-tron-goi-ha-thanh-home-uy-tin-chuyen-nghiep": "/du-an/xay-nha-tron-goi-hathanhhome-cong-ty-xay-dung-uy-tin-chuyen-nghiep",
  "/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi-ha-thanh-home": "/du-an/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi",
  "/xay-nha-tron-goi-tai-phu-xuyen-hathanhhome": "/du-an/xay-nha-tron-goi-tai-phu-xuyen",
  "/cap-nhap-bao-gia-xay-nha-tron-goi-tai-nam-dinh-2026-chi-tiet-tung-hang-muc": "/du-an/cap-nhat-bao-gia-xay-nha-tron-goi-tai-nam-dinh-2026-chi-tiet-tung-hang-muc",
  "/bao-gia-nha-lien-ke-nam-2026": "/du-an/bao-gia-xay-nha-tron-goi-lien-ke-nam-2026",
  "/bao-gia-xay-nha-tai-phuong-hoanh-bo-quang-ninh": "/du-an/bao-gia-xay-nha-tron-goi-tai-phuong-hoanh-bo-quang-ninh",
  "/bao-gia-xay-nha-tron-goi-hathanhhome": "/du-an/bao-gia-xay-nha-tron-goi-hathanhhome-uy-tin-chat-luong",
  "/bao-gia-xay-nha-tron-goi-nam-2026": "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan-cho-gia-chu",
  "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan": "/bao-gia-xay-nha-tron-goi-nam-2026-cach-tinh-chi-phi-chuan-cho-gia-chu",
  "/bao-gia-xay-nha-tron-goi-tai-phuong-ngo-quyen-hai-phong": "/du-an/bao-gia-xay-nha-tron-goi-2026-phuong-ngo-quyen-hai-phong",
  "/bao-gia-xay-nha-tron-goi-tai-thuong-tin-ha-noi": "/bao-gia-xay-nha-tron-goi-tai-thuong-tin-ha-noi-khong-phat-sinh-chi-phi",
  "/contact": "/lien-he",
  "/mau-nha-biet-thu-dep-nhat-2026": "/mau-thiet-ke-kien-truc/mau-nha-biet-thu-dep-2026",
  "/xay-nha-tron-goi-ba-vi-ho-tro-20/7-cong-ty-xay-dung-uy-tin": "/du-an/xay-nha-tron-goi-ba-vi-ho-tro-20-7-cong-ty-xay-dung-uy-tin",
  "/xay-nha-tron-goi-tai-bac-giang": "/du-an/xay-nha-tron-goi-tai-bac-giang-cong-ty-xay-nha-tron-goi-uy-tin",
  "/xay-nha-tron-goi-tai-tay-ho": "/du-an/xay-nha-tron-goi-tay-ho-bao-gia-chi-tiet-minh-bach",
  "/xay-nha-tron-goi-tai-thai-binh-bao-gia-quy-trinh-tu-a-z": "/du-an/xay-nha-tron-goi-tai-thai-binh-bao-gia-nam-2026-quy-trinh-tu-a-z",
  "/xem-ngay-dong-tho-dup-chu-nha-phan-len-nhu-dieu-gap-gio": "/tin-tuc/xem-ngay-dong-tho-giup-chu-nha-phat-len-nhu-dieu-gap-gio",
  "/quy-trinh-ve-sinh-tuong-truoc-khi-son-ngoai-that-3": "/tin-tuc/quy-trinh-ve-sinh-tuong-truoc-khi-son-ngoai-that",
  "/dich-vu/xay-nha-tron-goi-ha-thanh-home-uy-tin-chuyen-nghiep": "/du-an/xay-nha-tron-goi-hathanhhome-cong-ty-xay-dung-uy-tin-chuyen-nghiep",
  "/dich-vu/bao-gia-xay-nha-tai-tien-du-bac-ninh-uy-tin-chat-luong": "/du-an/bao-gia-xay-nha-tron-goi-tai-tien-du-bac-ninh-uy-tin-chat-luong",
  "/dich-vu/bao-gia-xay-nha-tron-goi-tai-ninh-binh-moi-nhat-2026-cong-ty-xay-dung-uy-tin": "/du-an/bao-gia-xay-nha-tron-goi-tai-ninh-binh-nam-2026",
  "/thiet-ke-thi-cong-nha-pho-tron-goi-ha-noi-quy-trinh-chi-phi-va-cam-ket-tien-do/": "/tin-tuc/thiet-ke-thi-cong-nha-pho-tron-goi-ha-noi-quy-trinh-chi-phi-va-cam-ket-tien-do",
  "/thi-cong-nha-xuong-cong-nghiep/": "/tin-tuc/thi-cong-nha-xuong-cong-nghiep",
  "/dich-vu/xay-nha-tron-goi-tai-hai-duong-cap-nhap-bao-gia-moi-nhat-2026": "/du-an/xay-nha-tron-goi-tai-hai-duong-cap-nhat-bao-gia-moi-nhat2026",
  "/dich-vu/xay-nha-tron-goi-o-hoang-mai-bao-gia-chi-tiet-nhat-hathanhhome": "/du-an/xay-nha-tron-goi-o-hoang-mai-bao-gia-chi-tiet",
  "/dich-vu/xat-nha-tron-goi-tai-phuc-tho-cap-nhap-bao-gia-moi-nhat-hien-nay": "/du-an/xay-nha-tron-goi-phuc-tho-cap-nhat-bao-gia-nam-2026",
  "/dich-vu/xay-nha-tron-goi-tai-dong-anh-don-vi-thi-cong-chuyen-nghiep-ha-thanh-home": "/du-an/xay-nha-tron-goi-dong-anh-don-vi-thi-cong-chuyen-nghiep",
  "/cong-ty-xay-dung-nha-o-uy-tin-ha-noi/": "/du-an/cong-ty-xay-dung-nha-o-uy-tin-ha-noi",
  "/dich-vu/bao-gia-xay-nha-tron-goi-tai-ha-noi-minh-bach-ha-thanh-home": "/du-an/bao-gia-xay-nha-tron-goi-tai-ha-noi-2026",
  "/dich-vu/xay-nha-tron-goi-tai-noi-bai-ha-noi": "/du-an/xay-nha-tron-goi-xa-noi-bai-ha-noi",
  "/thiet-ke-thi-cong-nha-o-ket-hop-kinh-doanh-toi-uu-mat-tien-va-cong-nang/": "/tin-tuc/thiet-ke-thi-cong-nha-o-ket-hop-kinh-doanh-toi-uu-mat-tien-va-cong-nang",
  "/dich-vu/xay-nha-tron-goi-tai-son-tay-cam-ket-chuan-tien-do": "/du-an/xay-nha-tron-goi-son-tay-cam-ket-chuan-tien-do",
  "/xay-nha-cho-nguoi-ban-ron-vi-sao-nen-chon-dich-vu-thiet-ke-thi-cong-tron-goi/": "/tin-tuc/xay-nha-cho-nguoi-ban-ron-vi-sao-nen-chon-dich-vu-thiet-ke-thi-cong-tron-goi",
  "/thi-cong-fit-out-van-phong-ha-noi-hoan-thien-mat-bang-tho-thanh-van-phong-chuyen-nghiep/": "/tin-tuc/thi-cong-fit-out-van-phong-ha-noi-hoan-thien-mat-bang-tho-thanh-van-phong-chuyen-nghiep",
  "/thi-cong-nha-theo-ban-ve-co-san-ha-noi/": "/tin-tuc/thi-cong-nha-theo-ban-ve-co-san-ha-noi",
  "/xay-biet-thu-san-vuon-ven-do-ha-noi-chi-phi-thiet-ke-va-thi-cong-tron-goi/": "/tin-tuc/xay-biet-thu-san-vuon-ven-do-ha-noi-chi-phi-thiet-ke-va-thi-cong-tron-goi",
  "/xay-nha-tron-goi-tai-nam-dinh/": "/du-an/xay-nha-tron-goi-tai-nam-dinh",
  "/thi-cong-nha-xuong-cho-doanh-nghiep-fdi-tieu-chuan-ho-so-va-tien-do-ban-giao/": "/tin-tuc/thi-cong-nha-xuong-cho-doanh-nghiep-fdi-tieu-chuan-ho-so-va-tien-do-ban-giao",
  "/thiet-ke-va-thi-cong-noi-that-nha-pho/": "/tin-tuc/thiet-ke-va-thi-cong-noi-that-nha-pho",
  "/xay-nha-khong-can-xin-phep-co-can-thong-bao-khoi-cong-khong/": "/tin-tuc/xay-nha-khong-can-xin-phep-co-can-thong-bao-khoi-cong-khong",
  "/xay-nha-sau-1-7-2026-chu-nha-can-biet-gi-de-khong-sai-quy-dinh/": "/tin-tuc/xay-nha-sau-1-7-2026-chu-nha-can-biet-gi-de-khong-sai-quy-dinh",
  "/du-toan-xay-nha-tron-goi-cach-doc-bang-du-toan-de-tranh-thieu-hang-muc/": "/tin-tuc/du-toan-xay-nha-tron-goi-cach-doc-bang-du-toan-de-tranh-thieu-hang-muc",
  "/xay-nha-tron-goi-uy-tin-tai-ha-noi/": "/du-an/xay-nha-tron-goi-uy-tin-tai-ha-noi",
  "/thiet-ke-thi-cong-van-phong-hang-a-tieu-chuan-hoan-thien-cho-doanh-nghiep-chuyen-nghiep/": "/tin-tuc/thiet-ke-thi-cong-van-phong-hang-a-tieu-chuan-hoan-thien-cho-doanh-nghiep-chuyen-nghiep",
  "/xay-biet-thu-tron-goi/": "/tin-tuc/xay-biet-thu-tron-goi",
  "/dich-vu/xay-nha-tron-goi-tai-nam-dinh-cap-nhat-bao-gia-moi-nhat-2026": "/du-an/cap-nhat-bao-gia-xay-nha-tron-goi-tai-nam-dinh-2026-chi-tiet-tung-hang-muc",
  "/dich-vu/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi-ha-thanh-home": "/du-an/xay-nha-tron-goi-tai-xa-an-khanh-ha-noi",
  "/nha-duoi-500m2-co-can-xin-phep-xay-dung-khong-gia-chu-can-hieu-dung/": "/tin-tuc/nha-duoi-500m2-co-can-xin-phep-xay-dung-khong-gia-chu-can-hieu-dung",
  "/nang-cap-nha-xuong-dat-chuan-pccc-hang-muc-can-lam-truoc-khi-nghiem-thu/": "/tin-tuc/nang-cap-nha-xuong-dat-chuan-pccc-hang-muc-can-lam-truoc-khi-nghiem-thu",
  "/gia-xay-tho-biet-thu/": "/tin-tuc/gia-xay-tho-biet-thu",
  "/thi-cong-van-phong-cho-cong-ty-fdi-tieu-chuan-tien-do-va-quy-trinh-lam-viec/": "/tin-tuc/thi-cong-van-phong-cho-cong-ty-fdi-tieu-chuan-tien-do-va-quy-trinh-lam-viec",
  "/du-toan-xay-nha-va-bao-gia-xay-nha-khac-nhau-the-nao-gia-chu-can-hieu-dung/": "/tin-tuc/du-toan-xay-nha-va-bao-gia-xay-nha-khac-nhau-the-nao-gia-chu-can-hieu-dung",
  "/thiet-ke-thi-cong-biet-thu-tron-goi/": "/tin-tuc/thiet-ke-thi-cong-biet-thu-tron-goi",
  "/cach-lua-chon-nha-thau-xay-dung-uy-tin-4": "/tin-tuc/cach-lua-chon-nha-thau-xay-dung-uy-tin",
};

/** Return a destination only for an explicitly approved historical pathname. */
export function getLegacyRedirectTarget(pathname: string): string | undefined {
  return legacySeoRedirects[pathname];
}

export function isLegacyRedirectSource(pathname: string): boolean {
  return Boolean(getLegacyRedirectTarget(pathname));
}
